// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportTaskPlanner.TelegramBot.TaskReceiversManagement.Data;

#nullable disable

namespace ReportTaskPlanner.TelegramBot.Migrations.TaskReceiverDb
{
    [DbContext(typeof(TaskReceiverDbContext))]
    partial class TaskReceiverDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ReportTaskPlanner.TelegramBot.TaskReceiversManagement.Models.TaskReceiver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_enabled");

                    b.HasKey("Id")
                        .HasName("receiver_id");

                    b.ToTable("Task_Receivers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
