// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportTaskPlanner.TelegramBot.ApplicationTimeManagement.Data.TimeZoneDbData;

#nullable disable

namespace ReportTaskPlanner.TelegramBot.Migrations.TimeZoneDb
{
    [DbContext(typeof(TimeZoneDbContext))]
    [Migration("20250401170944_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ReportTaskPlanner.TelegramBot.ApplicationTimeManagement.Data.TimeZoneDbData.TimeZoneDbOptions", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Token")
                        .HasName("token");

                    b.ToTable("Time_Zone_Db_Options", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
