// <auto-generated />
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportTaskPlanner.TelegramBot.ReportTaskManagement.Data;

#nullable disable

namespace ReportTaskPlanner.TelegramBot.Migrations.ReportTaskDb
{
    [DbContext(typeof(ReportTaskDbContext))]
    [Migration("20250401172305_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("ReportTaskPlanner.TelegramBot.ReportTaskManagement.Models.ReportTask", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("task_text");

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "ReportTaskPlanner.TelegramBot.ReportTaskManagement.Models.ReportTask.Schedule#ReportTaskSchedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<bool>("IsPeriodic")
                                .HasColumnType("INTEGER")
                                .HasColumnName("task_schedule_is_periodic");

                            b1.Property<long>("TimeCreated")
                                .HasColumnType("INTEGER")
                                .HasColumnName("task_schedule_created_unix");

                            b1.Property<long>("TimeToNotify")
                                .HasColumnType("INTEGER")
                                .HasColumnName("task_schedule_notify_time");
                        });

                    b.HasKey("Id")
                        .HasName("task_id");

                    b.ToTable("Report_Tasks", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
